def pitchingCSVUpdate():
    with open("Pitching.csv", mode='r') as csvfile:
        teamsreader = csv.DictReader(csvfile)
        line_count = 0
        for row in teamsreader:
            if line_count!=0:
                sql = "INSERT INTO pitching VALUES ("
                sql += teamsreader['ID'] + ","
                sql += teamsreader['playerid'] + ","
                sql += teamsreader['yearID'] + ","
                sql += teamsreader['stint'] + ","
                sql += teamsreader['teamID'] + ","
                sql += teamsreader['W'] + ","
                sql += teamsreader['L'] + ","
                sql += teamsreader['G'] + ","
                sql += teamsreader['GS'] + ","
                sql += teamsreader['CG'] + ","
                sql += teamsreader['SHO'] + ","
                sql += teamsreader['SV'] + ","
                sql += teamsreader['IPouts'] + ","
                sql += teamsreader['H'] + ","
                sql += teamsreader['ER'] + ","
                sql += teamsreader['HR'] + ","
                sql += teamsreader['BB'] + ","
                sql += teamsreader['SO'] + ","
                sql += teamsreader['BAOpp'] + ","
                sql += teamsreader['ERA'] + ","
                sql += teamsreader['IBB'] + ","
                sql += teamsreader['WP'] + ","
                sql += teamsreader['HBP'] + ","
                sql += teamsreader['BK'] + ","
                sql += teamsreader['BFP'] + ","
                sql += teamsreader['GF'] + ","
                sql += teamsreader['R'] + ","
                sql += teamsreader['SH'] + ","
                sql += teamsreader['SF'] + ","
                sql += teamsreader['GIDP'] + ","
                sql += ";"
            line_count+=1